import bpy

from .import_textures import *
from .append_misc import THOMAS_RIG_LEGACY_APPEND_MISC
from .append_rig_base import THOMAS_RIG_LEGACY_APPEND_CAPE, THOMAS_RIG_LEGACY_APPEND_ELYTRA
from .armor_tab_set import THOMAS_RIG_ASSETS_ARMOR_TAB_OT_SET
from .armor import THOMAS_RIG_ARMOR_ADD
from .img_pack_reload import THOMAS_RIG_IMG_PACK, THOMAS_RIG_IMAGERELOAD
from .remove_rig_base import THOMAS_RIG_LEGACY_REMOVE_CAPE, THOMAS_RIG_LEGACY_REMOVE_ELYTRA
from .skin_download import THOMAS_RIG_SKIN_DOWNLOAD
from .tool_parent import THOMAS_RIG_TOOL_PARENT
from .rig_update import THOMAS_RIG_UPDATE_RIG
from .append_base_mesh import THOMAS_RIG_LEGACY_APPEND_BASE_MESH
from .clear_imported_textures import THOMAS_RIG_CLEAR_IMPORTED_TEXTURES


classes = (
    THOMAS_RIG_CLEAR_IMPORTED_TEXTURES,
    MC_TEXTURES_SKIP_OT_SET,
    MC_TEXTURES_IMPORT_OT_SET,
    THOMAS_RIG_SKIN_DOWNLOAD,
    THOMAS_RIG_ASSETS_ARMOR_TAB_OT_SET,
    THOMAS_RIG_ARMOR_ADD,
    THOMAS_RIG_TOOL_PARENT,
    THOMAS_RIG_LEGACY_APPEND_CAPE,
    THOMAS_RIG_LEGACY_REMOVE_CAPE,
    THOMAS_RIG_LEGACY_APPEND_ELYTRA,
    THOMAS_RIG_LEGACY_REMOVE_ELYTRA,
    THOMAS_RIG_LEGACY_APPEND_MISC,
    THOMAS_RIG_IMG_PACK,
    THOMAS_RIG_IMAGERELOAD,
    THOMAS_RIG_UPDATE_RIG,
    THOMAS_RIG_LEGACY_APPEND_BASE_MESH,
)

register, unregister = bpy.utils.register_classes_factory(classes)