"""
Storyboard Agent (Phase 2) — turns a SceneGraph into a per-scene LAYER PLAN.

PURE + deterministic (like scene_director): no I/O beyond the character registry,
so it's cheap to dry-run and easy to verify. It only ACTS when LAYERED_RENDER=1;
otherwise it's a no-op and the pipeline renders single-asset scenes exactly as
before (backward compatible).

CPU BUDGET (measured Phase-1 reality: ~11 min per AI still on the i5): we do NOT
make every scene a multi-AI-layer stack. The storyboard nominates ONE hero beat
for a full background+subject(+fx) stack with the reusable character, and gives the
rest a light single background layer (footage-first) — so a short costs ~1 AI
still, not six. The FFmpeg Layer Composer (Phase 3) consumes scene.visual.layers.
"""
from __future__ import annotations

from ..config import settings
from ..schemas.scene import Layer, SceneGraph
from . import character as char

# Small, anime-first FX palette per niche (loopable transparent assets in
# data/assets/fx/). Screen-blended foreground for cinematic depth — never clichéd.
# CPU-cheap, loopable monochrome textures in data/assets/fx/ (generated by
# scripts/make_fx_assets.py). fx[0] is the one the hero stack screen-blends.
_FX: dict[str, list[str]] = {
    "cybersecurity": ["scanlines.png", "glow.png", "grain.png"],
    "usa_history":   ["grain.png", "glow.png"],
    "default":       ["grain.png"],
}


def _hero_index(graph: SceneGraph) -> int:
    """Pick the single hero beat for the full layered stack: the first scene the
    Director flagged ai_video, else the first 'dramatic' beat, else scene 0."""
    for i, s in enumerate(graph.scenes):
        if s.visual.type == "ai_video" or s.visual.strategy == "ai_video":
            return i
    for i, s in enumerate(graph.scenes):
        if s.visual.scene_visual_type == "dramatic":
            return i
    return 0


def storyboard(graph: SceneGraph, *, character_name: str = "",
               character_desc: str = "", style: str = "") -> SceneGraph:
    """Populate scene.visual.layers (CPU-budgeted). No-op unless LAYERED_RENDER=1.
    If a character is given (and character_memory is on), the hero beat's SUBJECT
    layer is locked to that reusable character (stable seed + description)."""
    s = settings()
    if not s.layered_render:
        return graph                              # inert → unchanged pipeline

    story_key = graph.meta.video_id or graph.meta.title
    fx_pool = _FX.get(graph.meta.niche, _FX["default"])
    hero = _hero_index(graph)

    ref = None
    if character_name and character_desc and s.character_memory:
        ref = char.get_or_create(story_key, character_name, character_desc,
                                  style=style)

    for i, scene in enumerate(graph.scenes):
        v = scene.visual
        bg_prompt = (v.visual_intent or v.query or " ".join(v.broll_keywords[:4]))
        if i == hero:
            # full hero stack: AI background (parallax-far) + character subject
            # (parallax-near) + one screen-blended fx. ONE AI still budget here.
            layers = [Layer(role="background", kind="ai_image", prompt=bg_prompt,
                            motion="zoom_in", parallax=0.12)]
            if ref:
                layers.append(Layer(
                    role="subject", kind="ai_image", character=ref.name,
                    prompt=char.character_prompt(ref, bg_prompt),
                    motion="zoom_out", parallax=0.6))
            if fx_pool:
                layers.append(Layer(role="fx", kind="asset",
                                    asset_path=fx_pool[0], blend="screen",
                                    opacity=0.35, parallax=0.85))
            v.layers = layers
        else:
            # light beats: a single background plane, FOOTAGE-first (cheap on CPU).
            # The resolver fills asset_path; parallax adds subtle life for free.
            v.layers = [Layer(role="background", kind="footage", query=bg_prompt,
                              motion=v.motion, parallax=0.1)]
    return graph
